### ISSUE TITLE
Qestions for Adaptation Strategy

### ISSUE THREAD

**Issue by BOBrown** [krumo/Detectron-DA-Faster-RCNN#12]
@krumo For domain adaptation of detectors from the source domain to the target domain, we always train from the ImageNet pre-trained model. However, in practical application, the pre-trained model on the source domain is usually available. Why don't we fine-tune from the pre-trained model on the source domain model, but fine-tune from the ImageNet pre-trained model. The latter seems to take more time. Could you explain the reason for this?

Look forward to your reply.

**Comment by krumo** [comment]
Hi @BOBrown , good question! I think this still remains an open question requiring further research. Theoretically, both ways could reach the same optimum. Practically, although some works claim that fine-tuning from the source data pre-trained model could get a better performance, I also observe same cases where source data pre-training and ImageNet pre-training achieve similar results. As far as I know, there's still not a paper proving that one way is obviously better than the other way with extensive theoretical analysis or experiments. 

For the reason why the author of DA Faster RCNN choose this training strategy, I would suggest you consult the original author.
