### ISSUE TITLE
Reproduce results (image/instance/consistency)

### ISSUE THREAD

**Issue by PolakUNI** [krumo/Detectron-DA-Faster-RCNN#14]
Hi! Nice work. I wanted to ask how to reproduce the results that you have on README:
**image | instance | consistency**
How do you activate/deactivate each of the respective setups (w/ image/instance/consistency)?
I have been trying several things, including changing the weights on configs but I am not sure whether this is how you do it. Also how to deal with the consistency.
Thanks!!!!

**Comment by krumo** [comment]
Hi, thanks for your interest!

The default setting of the code is **image+instance+consistency** adaptation. You could activate/deactivate each branch at [here](https://github.com/krumo/Detectron-DA-Faster-RCNN/blob/2a244d7608364be4edecb96c59e52dba7ff387ec/detectron/modeling/model_builder.py#L228) by just commenting corresponding lines. Please note that generally consistency branch requires the output of image-level branch and instance-level branch.
