### ISSUE TITLE
mAP or mAP50

### ISSUE THREAD

**Issue by Feobi1999** [krumo/Detectron-DA-Faster-RCNN#15]
![image](https://user-images.githubusercontent.com/35750924/98797173-337c6380-2447-11eb-916e-6630f5480605.png)
I found that it was written like this in the article. Is the evaluation index used in your experiment results AP (0.5:0.95) or AP50 (iou=0.5)? The term ‘mAP’ used in the article is a bit confusing.
Thanks!

**Comment by Feobi1999** [comment]
![微信图片_20201111180017](https://user-images.githubusercontent.com/35750924/98797624-ce753d80-2447-11eb-9fc0-fd0f25733ba1.png)

**Comment by krumo** [comment]
Thanks for your interest! The evaluation metrics is AP50.
