### ISSUE TITLE
Why are the annotations given for target domain dataset for training?

### ISSUE THREAD

**Issue by sangeetha-95** [krumo/Detectron-DA-Faster-RCNN#16]
I understand that while training both source and target domain datasets are provided. In the paper it is mentioned that only annotations for source domain is required. But in the experiments, both annotations files are requested while training. Can you explain why?

**Comment by krumo** [comment]
Hi, thanks for your interest!

As Detectron is designed for supervised learning, it requires to pass an annotation file for each dataset for training and testing. When I implemented the method, I didn' intend to make a huge change to the codebase. Thus, I follow the Detectron's way to create an annotation file with pseudo bboxes and pseudo masks for target domain dataset. You could check [convert_cityscapes_to_unlabeled_caronly_coco.py](https://github.com/krumo/Detectron-DA-Faster-RCNN/blob/2a244d7608364be4edecb96c59e52dba7ff387ec/tools/convert_cityscapes_to_unlabeled_caronly_coco.py#L124) to see how we generate pseudo bboxes and masks.
