### ISSUE TITLE
libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by benedictflorance** [krumo/Detectron-DA-Faster-RCNN#5]
Running 
`python2 tools/train_net.py --cfg configs/da_faster_rcnn_baselines/e2e_da_faster_rcnn_vgg16-sim10k.yaml` 
```
Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
    import cv2  # NOQA (Must import before importing caffe2 due to bug in cv2)
ImportError: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory
```
Running ffmpeg -v on the terminal, I get
```
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
```

Running
`python tools/train_net.py --cfg configs/da_faster_rcnn_baselines/e2e_da_faster_rcnn_vgg16-sim10k.yaml` throws this error.

```
Traceback (most recent call last):
  File "tools/train_net.py", line 38, in <module>
    from detectron.core.test_engine import run_inference
  File "/home/barock/detectron/detectron/core/test_engine.py", line 34, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/home/barock/detectron/detectron/core/rpn_generator.py", line 41, in <module>
    from detectron.datasets import task_evaluation
  File "/home/barock/detectron/detectron/datasets/task_evaluation.py", line 47, in <module>
    import detectron.datasets.json_dataset_evaluator as json_dataset_evaluator
  File "/home/barock/detectron/detectron/datasets/json_dataset_evaluator.py", line 34, in <module>
    import detectron.utils.boxes as box_utils
  File "/home/barock/detectron/detectron/utils/boxes.py", line 51, in <module>
    import detectron.utils.cython_bbox as cython_bbox
ImportError: /home/barock/detectron/detectron/utils/cython_bbox.so: undefined symbol: _Py_ZeroStruct
```

Kindly help me in resolving the error.

**Comment by krumo** [comment]
hi @benedictflorance , that's weird. To be honest, I have never encountered this problem before. Could you check whether your opencv is well installed? I used this line `pip install opencv-python` to install opencv before.

**Comment by benedictflorance** [comment]
Yeah, I've tried downgrading libavcodec.so.57 to libavcode.so.56, tried uninstalling opencv and installing it back but it still throws the same error!

Running `import cv2` on pythons imports it correctly without any error but it throws `ImportError: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory` while running it on python2.

**Comment by JeromeMutgeert** [comment]
Maybe you can create a conda environment and install all dependencies in it from scratch. I've had no such problems using this approach. I'm on ubuntu 16.04 (however, the only real dependency this setup should have is linux x64). 
~~I'm not sure but I think I indeed installed opencv through pip in my conda env.~~

**Comment by JeromeMutgeert** [comment]
I just checked, I am usinig the package "py-opencv" from conda.

> $ conda list | grep opencv
libopencv                 3.4.2                hb342d67_1  
py-opencv                 3.4.2            py27hb342d67_1

**Comment by krumo** [comment]
I will close this issue because it seems to be more related to the base framework [Detectron](https://github.com/facebookresearch/Detectron) than this repo. Please let me know if you have any further question.
